-- MySQL schema (default)
CREATE DATABASE IF NOT EXISTS php_ajax_env CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE php_ajax_env;

CREATE TABLE IF NOT EXISTS notes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;